name 'robs_world'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures robs_world'
long_description 'Installs/Configures robs_world'
version '0.1.0'
